services: 
    postgres:
      image: postgres:16-alpine
      container_name: reliability-db
      restart: unless-stopped
      environment: 
        POSTGRES_USER: reliability_user
        POSTGRES_PASSWORD: reliability_pass
        POSTGRES_DB: reliability_db
      ports: 
        - "5432:5432"
      volumes: 
        - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

